resolver: nightly-2016-10-04
extra-deps: [ "ansigraph-0.3.0.2"
            , "markdown-unlit-0.4.0"
            , "clock-extras-0.1.0.2"
            , "haskell-src-meta-0.7.0"
            , "wreq-0.4.1.0"
            , "aeson-qq-0.8.1"
            , "next-ref-0.1.0.2"
            , "threads-extras-0.1.0.2"
            , "unagi-chan-0.4.0.0"
            , "vty-5.11"
            , "atomic-primops-0.8.0.4"
            , "microlens-0.4.7.0"
            , "microlens-mtl-0.1.10.0"
            , "microlens-th-0.4.1.0"
            , "http-client-0.4.31.1"
            , "http-client-tls-0.2.4.1"
            , "authenticate-oauth-1.5.1.2"
            ]
