flags: {}
extra-include-dirs:
- /usr/local/opt/openssl/include
extra-lib-dirs:
- /usr/local/opt/openssl/lib
docker:
  auto-pull: true
  enable: false
  repo: fpco/stack-build
extra-deps:
- threads-extras-0.1.0.2
- unagi-chan-0.4.0.0
resolver: lts-9.0
